### ISSUE TITLE
[astropy/astropy] --open-files did not catch ResourceWarning

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-openfiles#14]
If this is not really an issue, feel free to close, as I am not familiar with the internals of open files check. Example log: https://travis-ci.org/astropy/astropy/jobs/442639768

It seems weird to me that `--open-files` option still reported passing despite the presence of following warning:

```
sys:1: ResourceWarning: unclosed file <_io.BufferedWriter name=13>
```

*Moved from astropy/astropy#7913*

**Comment by drdavella** [comment]
I'm inclined to say that this is not actually an issue in this plugin. See the discussion here: https://github.com/astropy/astropy/issues/7913#issuecomment-431538395

**Comment by drdavella** [comment]
I'm reopening this issue and reinterpreting it as a feature request 😉. See #15 for related discussion.

**Comment by pllim** [comment]
This plugin should no longer be used, please see:

* https://github.com/astropy/pytest-openfiles/pull/44
