### ISSUE TITLE
Cause test failures instead of errors

### ISSUE THREAD

**Issue by drdavella** [astropy/pytest-openfiles#15]
This is a proposal for a change to the current behavior of the plugin. Currently when using `--open-files`, if a test leaves a file handle open, the test itself will still pass, but an error will also occur at test teardown.

It's possible to just cause the test to fail outright by customizing the `pytest_runtest_call` hook instead of `pytest_runtest_setup` and `pytest_runtest_teardown`, as we do currently.

The motivation for this is that it would allow us to cause test failures for `ResourceWarning`s as well. While it would be possible to cause errors for this in `pytest_runtest_teardown`, using test failures instead would cause the failure to occur with potentially more informative traceback information about the site of the `ResourceWarning`.

Some people might feel like it's useful to allow the test to pass and to have a separate error as we do currently, which I understand. However, I would argue that if you want to know if your test passes whether or not it leaves open file resources, you can just run without the `--open-files` option. But reasonable people may disagree 😉.

**Comment by pllim** [comment]
:+1: for informative traceback and one less hook to worry about.

**Comment by jdavies-st** [comment]
I agree this would be desirable.  Currently tracebacks from this plugin when a test errors (E) on teardown gives the traceback of the `pytest_runtest_teardown` hook function:

```
1448  _____ ERROR at teardown of test_nrc_wfss_background[NRCALONG-F250M-GRISMC] _____
1449
1450  item = <Function test_nrc_wfss_background[NRCALONG-F250M-GRISMC]>
1451  nextitem = <Function test_nrc_wfss_background[NRCALONG-F250M-GRISMR]>
1452
1453    def pytest_runtest_teardown(item, nextitem):
1454        # a "skipped" test will not have been called with
1455        # pytest_runtest_setup, so therefore won't have an
1456        # "open_files" member
1457        if (not item.config.getvalue('open_files') or not hasattr(item, 'open_files')):
1458            return
1459    
1460        start_open_files = item.open_files
1461        del item.open_files
1462    
1463        open_files = _get_open_file_list()
1464    
1465        # This works in tandem with the test_open_file_detection test to
1466        # ensure that it creates one extra open file.
1467        if item.name == 'test_open_file_detection':
1468            assert len(start_open_files) + 1 == len(open_files)
1469            return
1470    
1471        not_closed = set()
1472        open_files_ignore = item.config.getini('open_files_ignore')
1473        for filename in open_files:
1474            ignore = False
1475    
1476            for ignored in open_files_ignore:
1477    
1478                # Note that we use fnmatch rather than re for simplicity since
1479                # we are dealing with file paths - fnmatch works with the standard
1480                # * and ? wildcards in paths.
1481    
1482                if not os.path.isabs(ignored):
1483                    # Since the path is not absolute, we convert it to
1484                    # */<original_path> to make sure it matches absolute paths.
1485                    ignored = os.path.join('*', ignored)
1486    
1487                if fnmatch.fnmatch(filename, ignored):
1488                    ignore = True
1489                    break
1490    
1491            if ignore:
1492                continue
1493    
1494            if filename not in start_open_files:
1495                not_closed.add(filename)
1496    
1497        if len(not_closed):
1498            msg = ['File(s) not closed:']
1499            for name in not_closed:
1500                msg.append('  {0}'.format(name))
1501>           raise AssertionError('\n'.join(msg))
1502E           AssertionError: File(s) not closed:
1503E             /tmp/crds_cache/references/jwst/nircam/jwst_nircam_wfssbkg_0038.fits
1504
1505../../../virtualenv/python3.8.1/lib/python3.8/site-packages/pytest_openfiles/plugin.py:129: AssertionError
```

I.e. it echos back the plugin infrastructure, which is not useful at all.  Only the last two E lines are useful.

I've tried putting `__tracebackhide__ = True` into the hook function, but that does not work.  See https://github.com/pytest-dev/pytest/issues/283 for details.

A small workaround is to use `pytest --open-files --tb=line` to exclude the traceback echoing the plugin infrastructure, but it still doesn't give any good traceback info about how the file was left open within the test.  An example:

```
______________________ ERROR at teardown of test_table_with_unsigned_int _______________________
E   AssertionError: File(s) not closed:
      /private/var/folders/jg/by5st33j7ps356dgb4kn8w900001n5/T/tmp17g5sm4u/tmp.fits
```

Anyway, agree this would be worth investigating.  The trick is that whatever check is done has to happen after the test is called, and of course `pytest_runtest_teardown` is the natural place to do that.

**Comment by pllim** [comment]
This plugin should no longer be used, please see:

* https://github.com/astropy/pytest-openfiles/pull/44
