### ISSUE TITLE
Allow open files in doctests?

### ISSUE THREAD

**Issue by mhvk** [astropy/pytest-openfiles#18]
I like ensuring my tests do not leave any files open, but it is annoying to then also have to explicitly close any files in doctests (this is for my baseband package, which reads files, so almost all examples open files). Is it (or might it be) possible to exclude whole test files from `--open-files`?

**Comment by mhvk** [comment]
@astrofrog, @bsipocz - running into this issue again. Is it possible to exclude doctests from `--open-files`?

**Comment by bsipocz** [comment]
@mhvk - I'm not sure it's possible to do it, if it is @drdavella would know how.

**Comment by drdavella** [comment]
There are a few settings for ignoring open files tests. Have you tried adding your document directory to `open_files_ignore`?

(From the README):
```
[tool:pytest]
open_files_ignore = "/home/user/monty/output.log"
```

I'm not sure whether this currently works with a directory and/or whether it will work for documentation files. It's worth a try though.

**Comment by mhvk** [comment]
I thought about that, but it doesn't quite do the right thing: throughout my tests and documentation I am opening a given sample file, and in the tests I think it is useful to ensure I also close it, but in the documentation it distracts from the examples I give. I.e., ideally I'd like to exclude a file in which the test is written from being checked, rather than the file that is being opened...

**Comment by pllim** [comment]
This plugin should no longer be used, please see:

* https://github.com/astropy/pytest-openfiles/pull/44
