### ISSUE TITLE
Using duplicated opened files.

### ISSUE THREAD

**Issue by MiguelLatorre** [astropy/pytest-openfiles#23]
Opening twice the same file and closing only one of them goes undetected.
Opened files are returned in a **set** in function __get_open_file_list_.
```
    files = [x.path for x in p.open_files() if not x.path.endswith(suffixes)]
    return set(files)
```

Test to reproduce this scenario:
```
filename = 'x.txt'
h1 = open(filename, 'w')
h2 = open(filename, 'r')

def test():
    global h2

    h2.close()
```

**Comment by pllim** [comment]
This plugin should no longer be used, please see:

* https://github.com/astropy/pytest-openfiles/pull/44
