### ISSUE TITLE
data/open_file_detection.txt missing from released tar file

### ISSUE THREAD

**Issue by astrofrog** [astropy/pytest-openfiles#3]
This file needs to be included in the package data in ``setup.py``

**Comment by drdavella** [comment]
What do you think about excluding the test directory from the source release entirely? There's no equivalent to `astropy.test()` here, so there's not a great reason to include the tests in the release.

**Comment by astrofrog** [comment]
I'd still include it, just so we can still download the tar file and run the tests for the actual release easily. But yeah since it's not in the package it should be mentioned in the manifest not in setup.py.
