### ISSUE TITLE
v0.5.0 causes Travis CI to time out 

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-openfiles#31]
There was a job with `--open-files` on Travis CI using `tox`. It started to time out with `pytest-openfiles` 0.5.0 release. Things work again when we pinned it to 0.4.0.

In fact, when another PR (astropy/astropy#10159) globally applies `--open-files`, other jobs on Travis CI also timed out.

xref astropy/astropy#10160 and astropy/astropy#10164

**Comment by astrofrog** [comment]
@pllim - is this still an issue?

**Comment by pllim** [comment]
I guess not...? 😸
