### ISSUE TITLE
Conda packages for pytest-openfiles don't seem to know about minimum Python versions

### ISSUE THREAD

**Issue by hamogu** [astropy/pytest-openfiles#33]
Sherpa uses pytest-openfiles (through astropy) and we've seen our CI fail, once pytest-openfils dropped support for Python 3.5 (which we still have). It seems that this is due to the fact that the conda packages don't know about the minimum Python requirements:
https://github.com/sherpa/sherpa/pull/805
https://github.com/sherpa/sherpa/pull/806
https://github.com/sherpa/sherpa/pull/807

P.S.: I know that this is not the right repro to report conda packaging issues, but I don't know who builds the conda packages and where, so I'm hoping that that person reads this and can move the issue.

**Comment by hamogu** [comment]
I just learned that @Marie-Terrell is more clever than I am and actually found the correct repository:
https://github.com/astropy/conda-channel-astropy/issues/181

**Comment by bsipocz** [comment]
same comment applies here: https://github.com/astropy/pytest-doctestplus/issues/115#issuecomment-642916356
