### ISSUE TITLE
pytest-openfiles 0.5 has performance issue

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-openfiles#37]
`astropy` had to pin to 0.4, otherwise it took too long. @saimn said something about calling `gc` a lot at teardown.

**Comment by saimn** [comment]
Ref 0203b1b087475cb90de56e70eb7aeb010caee980

**Comment by pllim** [comment]
This plugin should no longer be used, please see:

* https://github.com/astropy/pytest-openfiles/pull/44
