### ISSUE TITLE
Any plans to release on conda?

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-openfiles#6]
I believe this was discussed but I can't find the issue here.

**Comment by bsipocz** [comment]
As I remember the issues was in pytest-astropy

**Comment by drdavella** [comment]
Yes it's here: https://github.com/astropy/pytest-astropy/issues/3

I'm closing this issue since I believe that releasing `pytest-astropy` on conda implies that all of its dependencies will be released on conda as well.
